### PR TITLE
Added all the CRUD operations

### PR DESCRIPTION
**Pull request by psychoactiv**
https://user-images.githubusercontent.com/68146697/162027795-0bb288c6-f8ec-4fb0-a294-9b1276d22336.mp4

- Added all the CRUD operations
- Added API calls and useReducer
- User can archive , trash, delete their note

### CODE REVIEW

**Review by shaksham08 — APPROVED** [review]
Code is well structured and clean.
Just try to create small PRs

**Review by cjinc121 — APPROVED** [review]
looks good 
api calls are correct,
just a sugggestion create smaller pr

**Review by JantuDeb — APPROVED** [review]
This is looks good. I would suggest you to create  pr request with smaller number of files

**Comment by psychoactiv** [comment]
> This is looks good. I would suggest you to create pr request with smaller number of files

sure

**Comment by psychoactiv** [comment]
> looks good api calls are correct, just a sugggestion create smaller pr

sure

**Comment by psychoactiv** [comment]
> Code is well structured and clean. Just try to create small PRs

sure

**Pull request merged**
